import { Schema, model, models } from "mongoose";

const NewProductSchema = new Schema(
  {
    sku: {
      type: String, //6 digit id for product generated by the system
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    slug: {
      type: String,
      unique: true,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    images_collection: [
      {
        image_link: { type: String, required: true },
        color: { type: String, required: true }, //hexcode color
        color_name: { type: String, required: true }, //color name
        images: [{ type: String, required: true }], //array of image links
        quantity: [
          {
            size: { type: String, required: true },
            quantity: { type: Number, required: true },
          },
        ],
      },
    ],
    price: {
      type: Number,
      required: true,
    },
    sale_price: {
      type: Number,
      required: false,
    },
    sale_price_effective_date: {
      type: String, // The date range during which the product is on sale separated by slash (/)
      required: false,
    },
    ratings: {
      type: Number,
      default: 0,
    },
    reviews_number: {
      type: Number,
      default: 0,
    },
    categories: [
      {
        title: { type: String, required: true },
        slug: { type: String, required: true },
      },
    ],
    product_highlights: {
      type: [String],
      required: false,
    },
    type: {
      type: [String],
      required: false,
    },
    material: {
      type: String,
      required: true,
    },
    sell_on_google_quantity: {
      type: Number,
      required: false,
    },
    pattern: {
      type: String,
      required: false,
    },
    fabric_type: {
      type: String,
      required: false,
    },
    care_instructions: {
      type: String,
      required: false,
    },
    origin: {
      type: String,
      required: true,
      default: "India",
    },
    availability: {
      type: String,
      required: true,
      enum: ["in_stock", "out_of_stock", "preorder", "backorder"],
      default: "in_stock",
    },
    availability_date: {
      type: Date, //will be needed if availability is preorder or backorder
      required: false,
    },
    brand: {
      type: String,
      required: true,
      default: "Chimanlal Suresh Kumar (CSK) Textiles",
    },
    faqs: [
      {
        question: { type: String, required: true },
        answer: { type: String, required: true },
      },
    ],
  },
  { timestamps: true }
);

const NewProduct = models.NewProducts || model("NewProducts", NewProductSchema);

export default NewProduct;
