import { Schema, model, models } from "mongoose";

const NewProductSchema = new Schema(
  {
    id:{
      type: String, //6 digit id for product generated by the system
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    slug: {
      type: String,
      unique: true,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    images: {
      type: [String],
      required: true,
    },
    image_link: {
      type: String,
      required: true,
    },
    price: {
      type: Number,
      required: true,
    },
    salePrice: {
      type: Number, 
      required: false,
    },
    salePriceEffectiveDate: {
      type: String, //The date range during which the product is on sale separated by slash (/)
      required: false,
    },
    availableSizes: [{
      size: { type: String, required: true },
      quantity: { type: Number, required: true },
    }],
    ratings: {
      type: Number,
      default: 0,
    },
    reviewsNumber: {
      type: Number,
      default: 0,
    },
    colorOptions: [
      {
        title: { type: String, required: true },
        color: { type: String, required: true },
        quantity: { type: Number, required: true },
      },
    ],
    categories: [
      {
        title: { type: String, required: true },
        slug: { type: String, required: true },
      },
    ],
    productHighlights: {
      type: [String],
      required: false,
    },
    type: {
      type: [String],
      required: false,
    },
    material: {
      type: String,
      required: true,
    },
    sell_on_google_quantity: {
      type: Number,
      required: false,
    },
    pattern: {
      type: String,
      required: false,
    },
    fabricType: {
      type: String,
      required: false,
    },
    careInstructions: {
      type: String,
      required: false,
    },
    origin: {
      type: String,
      required: true,
      default: "India",
    },
    availability: {
      type: String,
      required: true,
      enum: ["in_stock", "out_of_stock", "preorder", "backorder"],
      default: "in_stock",
    },
    availabilityDate: {
      type: Date, //will be needed if availability is preorder or backorder
      required: false,
    },
    brand: {
      type: String,
      required: true,
      default: "Chimanlal Suresh Kumar (CSK) Textiles",
    },
    faqs: [
      {
        question: { type: String, required: true },
        answer: { type: String, required: true },
      },
    ],
  },
  { timestamps: true }
);

// const Products = models.Products || model("Products", ProductSchema);

// export default Products;
